server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Foydalanuvchi kiritgan URL bo'yicha static fayl mavjud bo'lsa ko'rsatadi,
        # yo'q bo'lsa index.html ga yo'naltiradi (SPA uchun)
        try_files $uri /index.html;
    }

    error_page 404 /index.html;
}
